error.idgnr.not.supported=[IDGeneration Service] Current service doesn't support to generate next {0} id.

error.idgnr.tableid.notallocate.id=[IDGeneration Service] Unable to allocate a block of Ids. no row with table_name='{0}' exists in the {1} table.

error.idgnr.null.id=[IDGeneration Service] Although too many retries, unable to allocate a block of Ids.

error.idgnr.get.connection=[IDGeneration Service] We can't get a connection. So, unable to allocate a block of Ids.

error.idgnr.sequenceid.notallocate.id=[IDGeneration Service] Unable to allocate a block of Ids. Query for Id did not return a value.

error.idgnr.greater.maxid=[IDGeneration Service] Unable to provide an id.   No more Ids are available, the maximum {0} value has been reached.

error.idgnr.invalid.parameter=address in the configuration should be a valid IP or MAC Address

error.idgnr.select.idblock=[IDGeneration Service] Encountered an exception attempting to select the {0} table. 

error.idgnr.update.idblock=[IDGeneration Service] Encountered an exception attempting to update the {0} table.

warn.idgnr.update.idblock=[IDGeneration Service] Encountered an exception attempting to update the {0} table.  May be a transaction conflict. Try again. 

debug.idgnr.allocate.idblock=[IDGeneration Service] Allocating a new block of {0} ids for key_table {1}.

debug.idgnr.updated.norows=[IDGeneration Service] Update resulted in no rows being changed.

debug.idgnr.sequenceid.query=[IDGeneration Service] Requesting an Id using query: {0}

debug.idgnr.init.idblock=[IDGeneration Service] Insert initial id value for table_name='{0}'.
